class OrderAlreadyExistsException(Exception):
    ...

class OrderNotFoundException(Exception):
    ...
    
class UnauthorizedException(Exception):
    ...

class UnauthenticatedException(Exception):
    ...

class InvalidCredentialsException(Exception):
    ...